imagePullSecrets:
- anchore-enterprise-pullcreds
credentials:
  users:
  - username: admin
    password: foobar
anchoreEndpoint: "http://enterprise-enterprise-api.anchore-enterprise.svc.cluster.local:8228"
