name: Build & push values converter docker image

on:
  push:
    branches:
      - main
    paths:
      - 'scripts/enterprise-value-converter/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Login to DockerHub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          username: ${{ secrets.ANCHORECI_DOCKER_USER }}
          password: ${{ secrets.ANCHORECI_DOCKER_PASS }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: "{{defaultContext}}:scripts/enterprise-value-converter"
          push: true
          tags: |
            anchore/enterprise-helm-migrator:${{ github.sha }}
            anchore/enterprise-helm-migrator:latest
